version: '3'
services:
  spykard-app:
    restart: always
    env_file: .env
    build: .
    image: "spykard/popularplaces-app:latest" # goes to local registry
    ports:
      - "5005:5005"
    networks:
      - db_network
      - web_network
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "85:85"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - spykard-app
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge