"""Bug Fix

Revision ID: 2eac2d2e89da
Revises: 91c5b42654da
Create Date: 2021-10-12 01:57:09.127505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eac2d2e89da'
down_revision = '91c5b42654da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_PlaceGlobal_name', table_name='PlaceGlobal')
    op.create_index(op.f('ix_PlaceGlobal_name'), 'PlaceGlobal', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PlaceGlobal_name'), table_name='PlaceGlobal')
    op.create_index('ix_PlaceGlobal_name', 'PlaceGlobal', ['name'], unique=False)
    # ### end Alembic commands ###
