"""Fix Uniques

Revision ID: a59686620ab0
Revises: e0a4ae0c0983
Create Date: 2021-10-04 13:12:14.660051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59686620ab0'
down_revision = 'e0a4ae0c0983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('User_username_email_key', 'User', type_='unique')
    op.create_unique_constraint(None, 'User', ['email'])
    op.create_unique_constraint(None, 'User', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_constraint(None, 'User', type_='unique')
    op.create_unique_constraint('User_username_email_key', 'User', ['username', 'email'])
    # ### end Alembic commands ###
