"""New Search Settings for Turbo Search

Revision ID: aa5b0f6c94e9
Revises: 54d0fd20e668
Create Date: 2021-10-11 02:47:10.647318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5b0f6c94e9'
down_revision = '54d0fd20e668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('settings_save_places', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'settings_save_places')
    # ### end Alembic commands ###
