"""Bug Fix

Revision ID: 91c5b42654da
Revises: 0c3836454ec4
Create Date: 2021-10-12 01:49:52.750566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91c5b42654da'
down_revision = '0c3836454ec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('PlaceGlobal_name_key', 'PlaceGlobal', type_='unique')
    op.create_unique_constraint(None, 'PlaceGlobal', ['name', 'city_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'PlaceGlobal', type_='unique')
    op.create_unique_constraint('PlaceGlobal_name_key', 'PlaceGlobal', ['name'])
    # ### end Alembic commands ###
