"""New Search Settings for Turbo Search

Revision ID: 67fae47863f7
Revises: fabd92a12f67
Create Date: 2021-10-11 03:02:25.205515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fae47863f7'
down_revision = 'fabd92a12f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Search', sa.Column('settings_save_places', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Search', 'settings_save_places')
    # ### end Alembic commands ###
