"""New Search Settings for Turbo Search

Revision ID: 54d0fd20e668
Revises: 832697f67fd5
Create Date: 2021-10-11 02:15:03.861098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d0fd20e668'
down_revision = '832697f67fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Search', sa.Column('settings_osm_id', sa.Integer(), nullable=True))
    op.add_column('Search', sa.Column('settings_area_id', sa.Integer(), nullable=True))
    op.add_column('Search', sa.Column('settings_lat', sa.String(), nullable=True))
    op.add_column('Search', sa.Column('settings_lon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Search', 'settings_lon')
    op.drop_column('Search', 'settings_lat')
    op.drop_column('Search', 'settings_area_id')
    op.drop_column('Search', 'settings_osm_id')
    # ### end Alembic commands ###
