"""empty message

Revision ID: ed04df659d38
Revises: edeb8cb1558c
Create Date: 2021-10-04 17:16:26.748838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed04df659d38'
down_revision = 'edeb8cb1558c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('active', sa.Boolean(), nullable=False, server_default='True'))
    op.create_index(op.f('ix_User_active'), 'User', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_active'), table_name='User')
    op.drop_column('User', 'active')
    # ### end Alembic commands ###
