"""Flask Security Part 1

Revision ID: 1b3ebbfdebf2
Revises: a59686620ab0
Create Date: 2021-10-04 13:19:59.376837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3ebbfdebf2'
down_revision = 'a59686620ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Role',
    sa.Column('id', sa.Integer(), server_default=sa.text('nextval(\'"Role_id_seq"\')'), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Role_username'), 'Role', ['username'], unique=True)
    op.add_column('User', sa.Column('active', sa.Binary(), nullable=True))
    op.add_column('User', sa.Column('fs_uniquifier', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'User', ['fs_uniquifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User', type_='unique')
    op.drop_column('User', 'fs_uniquifier')
    op.drop_column('User', 'active')
    op.drop_index(op.f('ix_Role_username'), table_name='Role')
    op.drop_table('Role')
    # ### end Alembic commands ###
