"""New Search Settings for Turbo Search

Revision ID: fabd92a12f67
Revises: aa5b0f6c94e9
Create Date: 2021-10-11 03:01:36.906083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabd92a12f67'
down_revision = 'aa5b0f6c94e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Search', 'settings_all_places',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Search', 'settings_all_places',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
