"""empty message

Revision ID: 16e0e244a4c3
Revises: 91badbce1074
Create Date: 2021-10-04 17:24:20.556279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e0e244a4c3'
down_revision = '91badbce1074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('premium_enabled', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('User', sa.Column('premium_notified', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('User', sa.Column('last_login', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    op.add_column('User', sa.Column('superadmin', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('User', sa.Column('total_runs', sa.Integer(), server_default='0', nullable=True))
    op.add_column('User', sa.Column('active', sa.Boolean(), server_default='True', nullable=False))
    op.add_column('User', sa.Column('last_login_ip', sa.String(), server_default='', nullable=True))
    op.add_column('User', sa.Column('login_count', sa.Integer(), server_default='0', nullable=True))
    op.create_index(op.f('ix_User_active'), 'User', ['active'], unique=False)
    op.create_index(op.f('ix_User_premium_enabled'), 'User', ['premium_enabled'], unique=False)
    op.create_index(op.f('ix_User_superadmin'), 'User', ['superadmin'], unique=False)
    op.create_index(op.f('ix_User_total_runs'), 'User', ['total_runs'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_total_runs'), table_name='User')
    op.drop_index(op.f('ix_User_superadmin'), table_name='User')
    op.drop_index(op.f('ix_User_premium_enabled'), table_name='User')
    op.drop_index(op.f('ix_User_active'), table_name='User')
    op.drop_column('User', 'login_count')
    op.drop_column('User', 'last_login_ip')
    op.drop_column('User', 'active')
    op.drop_column('User', 'total_runs')
    op.drop_column('User', 'superadmin')
    op.drop_column('User', 'last_login')
    op.drop_column('User', 'premium_notified')
    op.drop_column('User', 'premium_enabled')
    # ### end Alembic commands ###
