"""New Search Settings for Turbo Search

Revision ID: 1f4b2a944c59
Revises: 67fae47863f7
Create Date: 2021-10-11 12:12:32.783730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f4b2a944c59'
down_revision = '67fae47863f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Search', 'settings_area_id')
    op.drop_column('Search', 'settings_osm_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Search', sa.Column('settings_osm_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('Search', sa.Column('settings_area_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
