"""Move Verified Columns to Global Place Table

Revision ID: 832697f67fd5
Revises: 16e0e244a4c3
Create Date: 2021-10-08 21:03:36.655371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '832697f67fd5'
down_revision = '16e0e244a4c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Place', 'latitude')
    op.drop_column('Place', 'place_id')
    op.drop_column('Place', 'longtitude')
    op.drop_column('Place', 'name_verified')
    op.drop_column('Place', 'type_verified')
    op.drop_column('Place', 'address_verified')
    op.add_column('PlaceGlobal', sa.Column('name_verified', sa.String(), nullable=True))
    op.add_column('PlaceGlobal', sa.Column('address_verified', sa.String(), nullable=True))
    op.add_column('PlaceGlobal', sa.Column('latitude', sa.Float(precision=53), nullable=True))
    op.add_column('PlaceGlobal', sa.Column('longtitude', sa.Float(precision=53), nullable=True))
    op.add_column('PlaceGlobal', sa.Column('type_verified', sa.String(), nullable=True))
    op.add_column('PlaceGlobal', sa.Column('place_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PlaceGlobal', 'place_id')
    op.drop_column('PlaceGlobal', 'type_verified')
    op.drop_column('PlaceGlobal', 'longtitude')
    op.drop_column('PlaceGlobal', 'latitude')
    op.drop_column('PlaceGlobal', 'address_verified')
    op.drop_column('PlaceGlobal', 'name_verified')
    op.add_column('Place', sa.Column('address_verified', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Place', sa.Column('type_verified', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Place', sa.Column('name_verified', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Place', sa.Column('longtitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('Place', sa.Column('place_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Place', sa.Column('latitude', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
