"""empty message

Revision ID: 43a89e836135
Revises: ed04df659d38
Create Date: 2021-10-04 17:22:22.690069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a89e836135'
down_revision = 'ed04df659d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_User_superadmin'), 'User', ['superadmin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_superadmin'), table_name='User')
    # ### end Alembic commands ###
